source/SampleWeb3/Controllers/Sample5Controller.cs
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using SampleWeb3.Services;
using System.Web.Mvc;

namespace SampleWeb3.Controllers
{
    public class Sample5Controller : Controller
    {
        // ASP.NET MVC 使用 jQuery EasyUI DataGrid - Checkbox 
        // http://kevintsengtw.blogspot.tw/2013/10/aspnet-mvc-jquery-easyui-datagrid_19.html

        private CustomerService service = new CustomerService();

        public ActionResult Index()
        {
            return View();
        }

        public ActionResult GetGridJSON(
            int page = 1,
            int rows = 10,
            string sort = "CustomerID",
            string order = "asc")
        {
            JObject jo = new JObject();
            jo.Add("total", service.TotalCount());
            jo.Add("rows", service.GetJsonForGrid(page, rows, sort, order));

            return Content(JsonConvert.SerializeObject(jo), "application/json");
        }
    }
}

source/SampleWeb3/Views/Sample5/Index.cshtml
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
@section styles
{
    <link href="~/Content/themes/default/easyui.css" rel="stylesheet"/>
    <link href="~/Content/bootstrap-switch.css" rel="stylesheet"/>
}

<h2>jQuery EasyUI DataGrid - Sample 5 - Checkbox</h2>

<div class="row-fluid">
    <div id="SelectMode" class="make-switch"
         data-on-label="多選" data-off-label="單選">
        <input type="checkbox" checked>
    </div>
    <input type="button" id="ButonClearChecked"
           value="Clear Checked" class="btn btn-info"/>
    <input type="button" id="ButonGetChecked"
           value="Get Checked" class="btn btn-success"/>
</div>
<br/>

<table id="DataGrid"></table>

<br/>
<p>
    <a href="http://kevintsengtw.blogspot.tw/2013/10/aspnet-mvc-jquery-easyui-datagrid_19.html" target="_blank">文章 - ASP.NET MVC 使用 jQuery EasyUI DataGrid - Checkbox</a>
</p>

@section scripts
{
    <script src="~/Scripts/jquery.easyui-1.4.3.min.js"></script>
    <script src="~/Scripts/bootstrap-switch.min.js"></script>
    <script type="text/javascript">
        $(function() {
            var getGridJSON = '@Url.Action("GetGridJSON", "Sample5")';
            Initialize_DataGrid(getGridJSON);

            $('#SelectMode').bootstrapSwitch('setState', true);
            $('#SelectMode').on('switch-change', function(e, data) {
                $('#DataGrid').datagrid('clearChecked');
                $('#DataGrid').datagrid('clearSelections');
                $('#DataGrid').datagrid({
                    singleSelect: !data.value
                });
            });

            $('#ButonClearChecked').click(function() {
                $('#DataGrid').datagrid('clearChecked');
                $('#DataGrid').datagrid('clearSelections');
            });

            $('#ButonGetChecked').click(function() {
                var checkedItems = $('#DataGrid').datagrid('getChecked');
                var names = [];
                $.each(checkedItems, function(index, item) {
                    names.push(item.CustomerID);
                });
                var result = names.join(",");
                alert(result);
            });
        });

        function Initialize_DataGrid(getGridJSON) {

            $('#DataGrid').datagrid({
                title: 'Northwind - Customer',
                url: getGridJSON,
                width: '800',
                height: '400',
                rownumbers: true,
                sortName: 'CustomerID',
                sortOrder: 'asc',
                multiSort: true,
                columns: [
                    [
                        { field: 'ck', checkbox: true },
                        { field: 'CustomerID', title: 'ID', sortable: true },
                        { field: 'CompanyName', title: 'CompanyName', sortable: true },
                        { field: 'ContactName', title: 'ContactName', sortable: true },
                        { field: 'ContactTitle', title: 'ContactTitle', sortable: true },
                        { field: 'Address', title: 'Address' },
                        { field: 'City', title: 'City', sortable: true },
                        { field: 'Region', title: 'Region' },
                        { field: 'Country', title: 'Country', sortable: true },
                        { field: 'Phone', title: 'Phone' },
                        { field: 'Fax', title: 'Fax' }
                    ]
                ],
                pagination: true,
                pagePosition: 'bottom',
                pageSize: 10
            });

            var pager = $('#DataGrid').datagrid('getPager');
            $(pager).pagination({
                pageSize: 10,
                showPageList: true,
                pageList: [10, 20, 50],
                beforePageText: '第',
                afterPageText: '頁 , 共 {pages} 頁',
                displayMsg: '顯示 {from} 到 {to} 筆資料 , 共 {total} 筆資料'
            });
        }
    </script>
}