source/SampleWeb4/Controllers/ProductController.cs
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using SampleWeb4.Models;
using System.Linq;
using System.Web.Mvc;

namespace SampleWeb4.Controllers
{
    public class ProductController : Controller
    {
        private Northwind db = new Northwind();

        public ActionResult GetByCategory(int? categoryId = null)
        {
            if (!categoryId.HasValue)
            {
                return new EmptyResult();
            }

            var products = db.Products
                             .Where(x => x.CategoryID == categoryId.Value)
                             .OrderBy(x => x.ProductID);

            return PartialView("_GetByCategory", products.ToList());
        }

        public ActionResult GetJsonByCategory(int? categoryId = null)
        {
            var products = db.Products
                .Where(x => x.CategoryID == categoryId.Value)
                .OrderBy(x => x.ProductID);

            JArray ja = new JArray();

            foreach (var item in products)
            {
                var itemObject = new JObject
                {
                    {"CategoryID", item.CategoryID},
                    {"ProductID", item.ProductID},
                    {"ProductName", item.ProductName},
                    {"QuantityPerUnit", item.QuantityPerUnit},
                    {"UnitPrice", item.UnitPrice},
                    {"UnitsInStock", item.UnitsInStock},
                    {"UnitsOnOrder", item.UnitsOnOrder}
                };
                ja.Add(itemObject);
            }

            return Content(JsonConvert.SerializeObject(ja), "application/json");
        }

    }
}

source/SampleWeb4/Controllers/Sample6Controller.cs
using System.Linq;
using System.Web.Mvc;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using SampleWeb4.Models;

namespace SampleWeb4.Controllers
{
    public class Sample6Controller : Controller
    {
        // ASP.NET MVC 使用 jQuery EasyUI DataGrid - 顯示 Details（使用 PartialView） 
        // http://kevintsengtw.blogspot.tw/2013/10/aspnet-mvc-jquery-easyui-datagrid_21.html

        // ASP.NET MVC 使用 jQuery EasyUI DataGrid - 顯示 Details（Sub DataGrid） 
        // http://kevintsengtw.blogspot.tw/2013/10/aspnet-mvc-jquery-easyui-datagrid_22.html

        private Northwind db = new Northwind();

        public ActionResult Index()
        {
            return View();
        }

        public ActionResult Index2()
        {
            return View();
        }

        public ActionResult GetGridJSON()
        {
            var categories = db.Categories.OrderBy(x => x.CategoryID);

            JArray ja = new JArray();

            foreach (var item in categories)
            {
                var itemObject = new JObject
                                 {
                                     { "CategoryID", item.CategoryID },
                                     { "CategoryName", item.CategoryName },
                                     { "Description", item.Description }
                                 };
                ja.Add(itemObject);
            }

            int count = categories.Count();

            JObject result = new JObject();
            result.Add("total", count);
            result.Add("rows", ja);

            return Content(JsonConvert.SerializeObject(result), "application/json");
        }
    }
}

source/SampleWeb4/Views/Sample6/Index.cshtml
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
@section styles
{
    <link href="~/Content/themes/default/easyui.css" rel="stylesheet"/>
}
<div class="page-header">
    <h2>jQuery EasyUI DataGrid - Sample 6-1 - 顯示 Details（使用 PartialView）</h2>
</div>

<table id="DataGrid"></table>

<br/>
<p>
    <a href="http://kevintsengtw.blogspot.tw/2013/10/aspnet-mvc-jquery-easyui-datagrid_21.html" target="_blank">文章 - ASP.NET MVC 使用 jQuery EasyUI DataGrid - 顯示 Details（使用 PartialView）</a>
</p>

@section scripts
{
    <script src="~/Scripts/jquery.easyui-1.4.3.min.js"></script>
    <script src="~/Scripts/datagrid-detailview.js"></script>
    <script type="text/javascript">
        $(function() {
            $('#DataGrid').datagrid({
                title: 'Northwind - Category',
                url: '@Url.Action("GetGridJSON", "Sample6")',
                width: '800',
                height: '400',
                rownumbers: true,
                columns: [
                    [
                        { field: 'ck', checkbox: true },
                        { field: 'CategoryID', title: 'ID' },
                        { field: 'CategoryName', title: 'Name' },
                        { field: 'Description', title: 'Description', width: 600 }
                    ]
                ],
                view: detailview,
                detailFormatter: function(index, row) {
                    return '<div id="ddv-' + index + '" style="padding:5px;"></div>';
                },
                onExpandRow: function(index, row) {
                    $('#ddv-' + index).panel({
                        border: false,
                        cache: false,
                        href: '@Url.Action("GetByCategory", "Product", new { categoryId = "_id_" })'
                            .replace("_id_", row.CategoryID),
                        onLoad: function() {
                            $('#DataGrid').datagrid('fixDetailRowHeight', index);
                        }
                    });
                    $('#DataGrid').datagrid('fixDetailRowHeight', index);
                }
            });
        });
    </script>
}

source/SampleWeb4/Views/Sample6/Index2.cshtml
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
@section styles
{
    <link href="~/Content/themes/default/easyui.css" rel="stylesheet"/>
}
<div class="page-header">
    <h2>jQuery EasyUI DataGrid - Sample 6-2 - 顯示 Details（Sub DataGrid） </h2>
</div>

<table id="DataGrid"></table>

<br/>
<p>
    <a href="http://kevintsengtw.blogspot.tw/2013/10/aspnet-mvc-jquery-easyui-datagrid_22.html" target="_blank">文章 - ASP.NET MVC 使用 jQuery EasyUI DataGrid - 顯示 Details（Sub DataGrid）</a>
</p>

@section scripts
{
    <script src="~/Scripts/jquery.easyui-1.4.3.min.js"></script>
    <script src="~/Scripts/datagrid-detailview.js"></script>
    <script type="text/javascript">
        $(function() {
            $('#DataGrid').datagrid({
                title: 'Northwind - Category',
                url: '@Url.Action("GetGridJSON", "Sample6")',
                width: '800',
                height: '400',
                rownumbers: true,
                columns: [
                    [
                        { field: 'ck', checkbox: true },
                        { field: 'CategoryID', title: 'ID' },
                        { field: 'CategoryName', title: 'Name' },
                        { field: 'Description', title: 'Description', width: 600 }
                    ]
                ],
                view: detailview,
                detailFormatter: function(index, row) {
                    return '<div style="padding:2px"><table id="ddv-' + index + '"></table></div>';
                },
                onExpandRow: function(index, row) {
                    $('#ddv-' + index).datagrid({
                        url: '@Url.Action("GetJsonByCategory", "Product", new { categoryId = "_id_" })'
                            .replace("_id_", row.CategoryID),
                        fitColumns: true,
                        singleSelect: true,
                        rownumbers: true,
                        loadMsg: '',
                        height: 'auto',
                        columns: [
                            [
                                { field: 'CategoryID', title: 'CategoryID' },
                                { field: 'ProductID', title: 'ProductID' },
                                { field: 'ProductName', title: 'Name' },
                                { field: 'QuantityPerUnit', title: 'Quantity Per Unit' },
                                { field: 'UnitPrice', title: 'Unit Price' },
                                { field: 'UnitsInStock', title: 'Units In Stock' },
                                { field: 'UnitsOnOrder', title: 'Units On Order' }
                            ]
                        ],
                        onResize: function() {
                            $('#DataGrid').datagrid('fixDetailRowHeight', index);
                        },
                        onLoadSuccess: function() {
                            setTimeout(function() {
                                $('#DataGrid').datagrid('fixDetailRowHeight', index);
                            }, 0);
                        }
                    });
                    $('#DataGrid').datagrid('fixDetailRowHeight', index);
                }
            });
        });
    </script>
}