source/SampleWeb/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace SampleWeb.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

source/SampleWeb/Controllers/Sample1Controller.cs
using System.Linq;
using System.Web.Mvc;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using SampleWeb.Models;

namespace SampleWeb.Controllers
{
    public class Sample1Controller : Controller
    {
        // ASP.NET MVC 使用 jQuery EasyUI DataGrid 基礎篇 
        // http://kevintsengtw.blogspot.tw/2013/10/aspnet-mvc-jquery-easyui-datagrid.html

        private Northwind db = new Northwind();

        public ActionResult Index()
        {
            return View();
        }

        public ActionResult GetGridJSON()
        {
            var categories = db.Categories.OrderBy(x => x.CategoryID);

            JArray ja = new JArray();

            foreach (var item in categories)
            {
                var itemObject = new JObject
                                 {
                                     { "CategoryID", item.CategoryID },
                                     { "CategoryName", item.CategoryName },
                                     { "Description", item.Description }
                                 };
                ja.Add(itemObject);
            }

            int count = categories.Count();

            JObject result = new JObject();
            result.Add("total", count);
            result.Add("rows", ja);

            return Content(JsonConvert.SerializeObject(result), "application/json");
        }
    }
}

source/SampleWeb/Controllers/Sample2Controller.cs
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using SampleWeb.Services;
using System.Web.Mvc;

namespace SampleWeb.Controllers
{
    public class Sample2Controller : Controller
    {
        // ASP.NET MVC 使用 jQuery EasyUI DataGrid 分頁功能 (DataGrid Pagination)
        // http://kevintsengtw.blogspot.tw/2013/10/aspnet-mvc-jquery-easyui-datagrid_8.html

        private CustomerService service = new CustomerService();

        public ActionResult Index()
        {
            return View();
        }

        public ActionResult GetGridJSON(
            int page = 1,
            int rows = 10,
            string sort = "CustomerID",
            string order = "asc")
        {
            JObject jo = new JObject();
            jo.Add("total", service.TotalCount());
            jo.Add("rows", service.GetJsonForGrid(page, rows));

            return Content(JsonConvert.SerializeObject(jo), "application/json");
        }
    }
}

source/SampleWeb/Controllers/Sample3Controller.cs
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using SampleWeb.Services;
using System.Web.Mvc;

namespace SampleWeb.Controllers
{
    public class Sample3Controller : Controller
    {
        // ASP.NET MVC 使用 jQuery EasyUI DataGrid - 排序 (Sorting) 
        // http://kevintsengtw.blogspot.tw/2013/10/aspnet-mvc-jquery-easyui-datagrid_9.html

        private CustomerService service = new CustomerService();

        public ActionResult Index()
        {
            return View();
        }

        public ActionResult GetGridJSON(
            int page = 1,
            int rows = 10,
            string sort = "CustomerID",
            string order = "asc")
        {
            JObject jo = new JObject();
            jo.Add("total", service.TotalCount());
            jo.Add("rows", service.GetJsonForGrid(page, rows, sort, order));

            return Content(JsonConvert.SerializeObject(jo), "application/json");
        }
    }
}

source/SampleWeb/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

source/SampleWeb/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

source/SampleWeb/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="jumbotron">
    <h1>ASP.NET</h1>
    <p class="lead">ASP.NET is a free web framework for building great Web sites and Web applications using HTML, CSS and JavaScript.</p>
    <p>
        <a href="http://asp.net" class="btn btn-primary btn-lg">Learn more &raquo;</a>
    </p>
</div>

<div class="row">
    <div class="col-md-4">
        <h2>Sample 1</h2>
        <p>
            ASP.NET MVC 使用 jQuery EasyUI DataGrid 基礎篇.
        </p>
        <p>
            <a class="btn btn-default" href="@Url.Action("Index", "Sample1")">Learn more &raquo;</a>
        </p>
    </div>
    <div class="col-md-4">
        <h2>Sample 2</h2>
        <p>
            ASP.NET MVC 使用 jQuery EasyUI DataGrid 分頁功能 (DataGrid Pagination).
        </p>
        <p>
            <a class="btn btn-default" href="@Url.Action("Index", "Sample2")">Learn more &raquo;</a>
        </p>
    </div>
    <div class="col-md-4">
        <h2>Sample 3</h2>
        <p>
            ASP.NET MVC 使用 jQuery EasyUI DataGrid - 排序 (Sorting).
        </p>
        <p>
            <a class="btn btn-default" href="@Url.Action("Index", "Sample3")">Learn more &raquo;</a>
        </p>
    </div>
</div>